### ISSUE TITLE
botにDMを送るとエラーを吐く

### ISSUE THREAD

**Issue by Huyu2239** [ichidaisai/kanri-chan#37]
```
[2023-05-23 11:17:33] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
     await coro(*args, **kwargs)
   File "/app/cogs/message_read_state.py", line 60, in on_message
     if message.channel.category_id not in (
 AttributeError: 'DMChannel' object has no attribute 'category_id'
```

**Comment by Huyu2239** [comment]
[fix: DMでのmessageとreactionイベントを無視](https://github.com/ichidaisai/kanri-chan/commit/dd0ae9ed9206fa214de20279cd215ee3820d92d6) にて修正
