### ISSUE TITLE
メッセージ転送が動かない

### ISSUE THREAD

**Issue by Huyu2239** [ichidaisai/kanri-chan#46]
カフェ、模擬カテゴリに25以上チャンネルが作成されたため、ViewにSelectを追加する段階でエラーが出る
```
kanri-chan-app-1       | [2023-06-22 09:28:54] [ERROR   ] discord.client: Ignoring exception in on_ready
kanri-chan-app-1       | Traceback (most recent call last):
kanri-chan-app-1       |   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
kanri-chan-app-1       |     await coro(*args, **kwargs)
kanri-chan-app-1       |   File "/app/main.py", line 48, in on_ready
kanri-chan-app-1       |     await message_relay.setup_select(channel)
kanri-chan-app-1       |   File "/app/cogs/message_relay.py", line 84, in setup_select
kanri-chan-app-1       |     await channel.send(
kanri-chan-app-1       |   File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1538, in send
kanri-chan-app-1       |     data = await state.http.send_message(channel.id, params=params)
kanri-chan-app-1       |   File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 744, in request
kanri-chan-app-1       |     raise HTTPException(response, data)
kanri-chan-app-1       | discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
kanri-chan-app-1       | In components.0.components.0.options: Must be between 1 and 25 in length.
```

**Comment by Huyu2239** [comment]
一時的に切り離し、需要が出てきたら戻す
削除はしない

**Comment by Huyu2239** [comment]
[fix: メッセージ転送機能を一時的に切り離し](https://github.com/ichidaisai/kanri-chan/commit/2b40392ea238b23b136a9e912d950c932859106b) にて修正
